
project_id = "kkebyebrhdpcwqnxhjcx"

[scheduled-update.secrets]
SUPABASE_URL = "vaulted"
SUPABASE_SERVICE_ROLE_KEY = "vaulted"
OXYLABS_USERNAME = "vaulted"
OXYLABS_PASSWORD = "vaulted"

[collect-laptops.secrets]
SUPABASE_URL = "vaulted"
SUPABASE_SERVICE_ROLE_KEY = "vaulted"
OXYLABS_USERNAME = "vaulted"
OXYLABS_PASSWORD = "vaulted"

