
// This file contains the most popular laptops that will be embedded in the HTML
export const criticalLaptops = [
  {
    "id": "popular-1",
    "asin": "B0BS3V4R2",
    "title": "MacBook Air M2",
    "current_price": 999.99,
    "original_price": 1199.99,
    "rating": 4.8,
    "rating_count": 2500,
    "image_url": "https://m.media-amazon.com/images/I/71TPda7cwUL._AC_SL1500_.jpg",
    "processor": "Apple M2",
    "ram": "8GB",
    "storage": "256GB SSD",
    "graphics": "Apple M2 GPU",
    "screen_size": "13.6 inch",
    "brand": "Apple",
    "total_reviews": 2500,
    "average_rating": 4.8,
  },
  {
    "id": "popular-2", 
    "asin": "B09QFYHNG",
    "title": "Dell XPS 13",
    "current_price": 899.99,
    "original_price": 999.99,
    "rating": 4.7,
    "rating_count": 1800,
    "image_url": "https://m.media-amazon.com/images/I/71RD3vsjIYL._AC_SL1500_.jpg",
    "processor": "Intel Core i5-1240P",
    "ram": "16GB",
    "storage": "512GB SSD",
    "graphics": "Intel Iris Xe",
    "screen_size": "13.4 inch",
    "brand": "Dell",
    "total_reviews": 1800,
    "average_rating": 4.7,
  },
  {
    "id": "popular-3",
    "asin": "B0BHC3GZ",
    "title": "Lenovo ThinkPad X1 Carbon",
    "current_price": 1299.99,
    "original_price": 1499.99,
    "rating": 4.6,
    "rating_count": 1200,
    "image_url": "https://m.media-amazon.com/images/I/71krmFGhX5L._AC_SL1500_.jpg",
    "processor": "Intel Core i7-1260P",
    "ram": "16GB",
    "storage": "1TB SSD",
    "graphics": "Intel Iris Xe",
    "screen_size": "14 inch",
    "brand": "Lenovo",
    "total_reviews": 1200,
    "average_rating": 4.6,
  }
] as const;

