// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkebyebrhdpcwqnxhjcx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtrZWJ5ZWJyaGRwY3dxbnhoamN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5OTY3MDgsImV4cCI6MjA1NTU3MjcwOH0._5FvHg_eP9Kc9pouNGlWVUu80zwv7mTTDqpBdriBuZw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);