
/**
 * Service for generating content with AI
 */
import { logError } from "../utils/errorHandler.ts";

/**
 * Generate content using DeepSeek API
 */
export async function generateContentWithDeepSeek(
  systemPrompt: string, 
  userPrompt: string, 
  apiKey: string
) {
  try {
    console.log("🤖 Calling DeepSeek API...");
    console.log(`📝 System prompt length: ${systemPrompt.length} characters`);
    console.log(`📝 User prompt length: ${userPrompt.length} characters`);
    
    if (!apiKey || apiKey.trim() === '') {
      throw new Error("Missing DeepSeek API key");
    }
    
    // DeepSeek API endpoint
    const apiUrl = "https://api.deepseek.com/v1/chat/completions";
    
    // Prepare the request
    const payload = {
      model: "deepseek-chat",
      messages: [
        {
          role: "system",
          content: systemPrompt
        },
        {
          role: "user",
          content: userPrompt
        }
      ],
      temperature: 0.7,
      max_tokens: 4000
    };
    
    // Make the request to DeepSeek API with proper headers
    const response = await fetch(apiUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${apiKey}`
      },
      body: JSON.stringify(payload)
    });
    
    // Log the response status
    console.log(`🔄 DeepSeek API response status: ${response.status}`);
    
    // Handle possible error responses
    if (!response.ok) {
      const errorData = await response.text();
      console.error(`❌ DeepSeek API error (${response.status}): ${errorData}`);
      
      if (response.status === 401) {
        throw new Error("DeepSeek API key is invalid or expired. Please check your API key.");
      } else {
        throw new Error(`DeepSeek API error: ${response.status} - ${errorData}`);
      }
    }
    
    // Process the successful response
    const data = await response.json();
    
    if (!data.choices || data.choices.length === 0) {
      console.error("❌ No content generated by DeepSeek");
      return "Error: Unable to generate content. Please try again later.";
    }
    
    const generatedContent = data.choices[0].message.content;
    console.log(`✅ Content generated successfully (${generatedContent.length} characters)`);
    
    return generatedContent;
  } catch (error) {
    // Improve error handling to provide better error messages
    let errorMessage = "Failed to generate content with DeepSeek.";
    
    if (error instanceof Error) {
      errorMessage = error.message;
      
      // Add more specific error messages
      if (errorMessage.includes("fetch failed")) {
        errorMessage = "Network error when connecting to DeepSeek. Please check your internet connection.";
      } else if (errorMessage.includes("timeout")) {
        errorMessage = "Request to DeepSeek timed out. The service might be experiencing high load.";
      }
    }
    
    logError(error, "Error calling DeepSeek API");
    console.error(`❌ DeepSeek API error: ${errorMessage}`);
    
    // Return a formatted error message that can be used in the blog post
    return `# Error Generating Content\n\nThere was a problem connecting to our AI service: ${errorMessage}\n\nPlease try again later.`;
  }
}
